name: Deploy to AWS ECS

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'package.json'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

env:
  AWS_REGION: eu-west-3
  ECS_CLUSTER_NAME: banana-cluster
  ECS_SERVICE_NAME: banana-front-service
  ECS_TASK_DEFINITION_FAMILY: banana-front

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Deploy to ECS
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
        ECS_CLUSTER_NAME: ${{ env.ECS_CLUSTER_NAME }}
        ECS_SERVICE_NAME: ${{ env.ECS_SERVICE_NAME }}
        ECS_TASK_DEFINITION_FAMILY: ${{ env.ECS_TASK_DEFINITION_FAMILY }}
        NEW_IMAGE: ${{ secrets.APP_IMAGE }}

    - name: Verify deployment
      run: |
        echo "🔍 Vérification du déploiement..."
        aws ecs describe-services \
          --cluster ${{ env.ECS_CLUSTER_NAME }} \
          --services ${{ env.ECS_SERVICE_NAME }} \
          --region ${{ env.AWS_REGION }} \
          --query 'services[0].{ServiceName:serviceName,Status:status,DesiredCount:desiredCount,RunningCount:runningCount,PendingCount:pendingCount}' \
          --output table

    - name: Get application URL
      run: |
        echo "🌐 URL de l'application:"
        aws elbv2 describe-load-balancers \
          --region ${{ env.AWS_REGION }} \
          --query 'LoadBalancers[?contains(LoadBalancerName, `banana-front`)].DNSName' \
          --output text | sed 's/^/http:\/\//'
